{
    'name': 'Coaching Management System',
    'version': '1.0.0',
    'sequence': 1,
    'summary': 'Manage students, teachers, classes, exams and fees',
    'category': 'Education',
    'author': 'Odoo Waves',
    'depends': ['base', 'account', 'website'],
    'data': [
        # 'security/security.xml',
        # 'security/record_rules.xml',
        'security/ir.model.access.csv',
        'views/res_partner.xml',
        'views/student_views.xml',
        'views/teacher_views.xml',
        'views/guardian_views.xml',
        'views/class_views.xml',
        'views/subject_views.xml',
        'views/exam_views.xml',
        'views/fee_structure_views.xml',
        'views/student_fee_views.xml',
        'views/coaching_menus.xml',
    ],
    'installable': True,
    'application': True,
}